// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductWeb.Persistence;

#nullable disable

namespace ProductWeb.Persistence.Migrations
{
    [DbContext(typeof(ProductWebDbContext))]
    [Migration("20220224081317_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductWeb.Domain.Entity.Product", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Picture")
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = "67f7fec6-9429-442e-90b2-b0480a907041",
                            Code = "3c8e0a27",
                            Name = "Product_1",
                            Picture = "http://www.example.com/551f4dd3",
                            Price = 24.05m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(8674)
                        },
                        new
                        {
                            Id = "09597e51-1f32-4eb9-bf72-6cbb0118851c",
                            Code = "5ae47bde",
                            Name = "Product_2",
                            Picture = "http://www.example.com/de1e89d1",
                            Price = 13.36m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(8830)
                        },
                        new
                        {
                            Id = "6f4e9622-1180-4412-a87d-3de537859472",
                            Code = "7f5f6990",
                            Name = "Product_3",
                            Picture = "http://www.example.com/564cb94e",
                            Price = 63.85m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9474)
                        },
                        new
                        {
                            Id = "6235ee0b-6d03-4990-8fe7-6f6b6ef6acc6",
                            Code = "2684e9c4",
                            Name = "Product_4",
                            Picture = "http://www.example.com/55fbcad9",
                            Price = 13.23m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9522)
                        },
                        new
                        {
                            Id = "f2a12bce-70f6-42c0-99e6-1aeb71d31061",
                            Code = "977a2e95",
                            Name = "Product_5",
                            Picture = "http://www.example.com/123192ef",
                            Price = 61.79m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9567)
                        },
                        new
                        {
                            Id = "9091879f-a0bb-4d49-9e9f-da60a055dd2d",
                            Code = "38eef0ba",
                            Name = "Product_6",
                            Picture = "http://www.example.com/d4934363",
                            Price = 12.30m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9675)
                        },
                        new
                        {
                            Id = "a4bc87c7-cbcf-4412-aae2-b4dd8532fc21",
                            Code = "1156e94f",
                            Name = "Product_7",
                            Picture = "http://www.example.com/ae5709c7",
                            Price = 26.82m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9724)
                        },
                        new
                        {
                            Id = "9e0cbdf7-78ef-49ec-ba3b-35f117423b5a",
                            Code = "b69d7cfb",
                            Name = "Product_8",
                            Picture = "http://www.example.com/5a7f789a",
                            Price = 29.86m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9774)
                        },
                        new
                        {
                            Id = "3422f4b5-1598-473c-98ab-d1d44e40a77b",
                            Code = "06922b75",
                            Name = "Product_9",
                            Picture = "http://www.example.com/be80d7db",
                            Price = 66.84m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9891)
                        },
                        new
                        {
                            Id = "3da17343-1219-4191-a3c9-21893cf54c75",
                            Code = "06730bdb",
                            Name = "Product_10",
                            Picture = "http://www.example.com/b67b5818",
                            Price = 35.60m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 192, DateTimeKind.Utc).AddTicks(9992)
                        },
                        new
                        {
                            Id = "33c734d6-a427-47d2-a41b-6a88f2c9cf9c",
                            Code = "d0ed1cda",
                            Name = "Product_11",
                            Picture = "http://www.example.com/435b7bd7",
                            Price = 34.51m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(41)
                        },
                        new
                        {
                            Id = "4f0dfc62-3583-40d3-9e60-d27984e9ec34",
                            Code = "a7eb6aa3",
                            Name = "Product_12",
                            Picture = "http://www.example.com/75abd660",
                            Price = 83.04m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(89)
                        },
                        new
                        {
                            Id = "f8e99452-e4e1-47d2-9dc2-5aa9caf65cb3",
                            Code = "d943e977",
                            Name = "Product_13",
                            Picture = "http://www.example.com/9c2fd2ec",
                            Price = 72.85m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(134)
                        },
                        new
                        {
                            Id = "756ab847-203a-48ad-8322-7a17d6541748",
                            Code = "9da8697b",
                            Name = "Product_14",
                            Picture = "http://www.example.com/34f6a685",
                            Price = 60.27m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(181)
                        },
                        new
                        {
                            Id = "3334528c-04a8-4b80-928e-9b22312545c4",
                            Code = "51648e89",
                            Name = "Product_15",
                            Picture = "http://www.example.com/58d375b7",
                            Price = 67.99m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(293)
                        },
                        new
                        {
                            Id = "9e95420b-0417-4f60-831f-1e40bc8857da",
                            Code = "f24628ff",
                            Name = "Product_16",
                            Picture = "http://www.example.com/fc0c018c",
                            Price = 74.69m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(353)
                        },
                        new
                        {
                            Id = "c9303654-745d-4049-bb8c-f6d3b48ad58a",
                            Code = "1095b7e3",
                            Name = "Product_17",
                            Picture = "http://www.example.com/b00d87a8",
                            Price = 8.13m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(398)
                        },
                        new
                        {
                            Id = "f0132c1a-dc8a-41c7-8ec8-91d163259a42",
                            Code = "490775e8",
                            Name = "Product_18",
                            Picture = "http://www.example.com/869df89f",
                            Price = 76.41m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(445)
                        },
                        new
                        {
                            Id = "61928688-9565-4dbd-9950-b4c3921115bc",
                            Code = "3ed8763b",
                            Name = "Product_19",
                            Picture = "http://www.example.com/014f3eeb",
                            Price = 23.09m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(484)
                        },
                        new
                        {
                            Id = "2c1a1bbf-cd4a-472e-a63f-3b8be9fb75ac",
                            Code = "6221159a",
                            Name = "Product_20",
                            Picture = "http://www.example.com/5b5d0e82",
                            Price = 7.97m,
                            UpdatedAt = new DateTime(2022, 2, 24, 8, 13, 17, 193, DateTimeKind.Utc).AddTicks(522)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
